### ISSUE TITLE
当进行缩放时，marker点会偏移

### ISSUE THREAD

**Issue by 3DMXM** [qiuxiang/canvaskit-map#1]
不知道哪里出了问题，大佬能否帮忙看看，代码： https://github.com/3DMXM/canvaskit-map-bug

![GIF2](https://github.com/user-attachments/assets/f5d27330-48eb-46c1-9de8-943e37fd5892)

**Comment by 3DMXM** [comment]
在线运行 Bug： https://stackblitz.com/edit/canvaskit-map-bug?file=src%2FApp.vue

**Comment by qiuxiang** [comment]
因为你的图片大小是 50x50，但实际显示的方块是左上角 10x10，marker 的中心和看起来小方块中心不一致

```
ctx.fillRect(0, 0, 50, 50);
```

改成这样看起来就不偏移了

**Comment by 3DMXM** [comment]
恩，将值改成一样是不偏移了，

还有另一个问题
当顶部存在 header的时候， event.coordinate 的值在不同的缩放情况下，是不一样的，  代码已经在上面更新
![image](https://github.com/user-attachments/assets/ddc753f4-74d4-4037-b0a9-108c49f38ae4)

**Comment by 3DMXM** [comment]
log输出的坐标是在不同缩放下，鼠标点击 红点 的坐标值 ( marker定义的坐标是 0, 0 )

**Comment by qiuxiang** [comment]
<del>
改成：
```css
.map {
  width: 100%;
  height: calc(100vh - 50px);
  position: relative;
}
.map > canvas {
  top: 0;
}
```
</del>

确实有问题，指针中心没考虑到位置偏移
